controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_main:
    path: /
    controller:
        App\Controller\main:
            index